name: CD with chained jobs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

  lint:
    needs: prepare
    runs-on: ubuntu-22.04

    steps:
      - name: Run linter
        run: echo "Linting..."

  test:
    needs: prepare
    runs-on: ubuntu-22.04

    steps:
      - name: Run tests
        run: echo "Testing..."

  build:
    needs: [lint, test]
    runs-on: ubuntu-22.04

    steps:
      - name: Build
        run: echo "Building..."
