name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages
        run: npm install

      - name: Run linter
        run: npm lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm build
