name: Debug workflow context & metadata

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      testBoolParam:
        description: some test testParam
        default: "true"
  issues:
    types:
      - opened

jobs:
  print-stuff:
    runs-on: ubuntu-22.04

    steps:
      - name: Print inputs details
        run: echo "${{ toJSON(inputs) }}"
