name: Debug workflow context & metadata

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      testBoolParam:
        description: some test testParam
        default: "true"
      deploy_env:
        description: test repository environments
        default: "dev"
        options:
          - "dev"
          - "test"
          - "prod"
  issues:
    types:
      - opened

jobs:
  print-stuff:
    runs-on: ubuntu-22.04
    environment: test

    steps:
      - name: Print inputs details
        run: echo "${{ toJSON(inputs) }}"
      - name: Dummy print secret
        run: echo ${{ secrets.MY_SECRET }}
